Added emulator for danfysik9100
ISISComputingGroup/EPICS-DeviceEmulator pull request #119
Opened 2021-06-30 13:29 UTC by SamJenkins1

Added an emulator for the danfysik9100 for use in testing https://github.com/ISISComputingGroup/IBEX/issues/6543

2021-07-19 13:29 UTC, JamesKingWork requested changes
Mostly good, just want to stick to naming conventions and also a couple of suggestions

2021-07-19 13:29 UTC, JamesKingWork commented on lewis_emulators/danfysik/interfaces/dfkps_9100.py
> +        def bit(condition):
Why are bit and ilk not defined by the base class? They seem to be repeated in each get_status

2021-07-19 13:29 UTC, JamesKingWork commented on lewis_emulators/danfysik/interfaces/dfkps_9100.py
> +        def bit(condition):
Can ilk also be named a bit better?

2021-07-19 13:29 UTC, JamesKingWork commented on lewis_emulators/danfysik/interfaces/__init__.py
> +__all__ = ['Danfysik8000StreamInterface', 'Danfysik8800StreamInterface', 'Danfysik9100StreamInterface']
Can we stick to 9X00 convention throughout

2021-07-27 11:05 UTC, SamJenkins1 commented on lewis_emulators/danfysik/interfaces/dfkps_9100.py
> +        def bit(condition):
I was just following how it was done in the other emulators, but I'll have a look into whether that can go into the base class.

2021-07-28 11:05 UTC, SamJenkins1 commented
Rebased onto master, and added review changes

2021-08-02 12:37 UTC, JamesKingWork commented on lewis_emulators/danfysik/interfaces/dfkps_9100.py
> +        def bit(condition):
Yeah generally makes sense to, it's just nice to leave it a bit tidier than we found it :) thank you for doing that

2021-08-02 12:38 UTC, JamesKingWork approved these changes
Looks good

2021-08-02 12:38 UTC, merged