Ticket651 hife cryomag psu emulator
ISISComputingGroup/EPICS-DeviceEmulator pull request #56
Opened 2019-10-15 09:00 UTC by ChrisColeExpControl

Emulator for use with CRYOSMS IOC. Currently able to send/recieve basic commands sufficiently accurately to test basic IOC function, but will need to be further deleoped in the future. Unsure if it is behaving exactly the same as the real device (may have incorrect in/out terminators). 

[Ticket](https://github.com/ISISComputingGroup/IBEX/issues/4826)

2019-10-15 18:31 UTC, DominicOram submitted a review, later dismissed
There's loads of code here that is superfluous to the actual ticket. I think ideally only the behaviour that is currently covered by the system tests and IOCs should be here otherwise it's just dead code. I have reviewed this dead code briefly as I assume you're working on it as part of another ticket?

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/device.py
> +            self.at_target = False
Can just be `self.target = self.output == self.ramp_target_value()`

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/device.py
> +            raise AssertionError("Invalid arg received")
Is it worth using an enum for `ramp_target`?

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +        print("Error occurred at {}: {}".format(request, error))
Why are we printing as well as logging?

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +        return target
Is it ok that this could potentially return None? Should this be an exception?

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +            dir_string = "ZERO"
This might be more nicely formatted as a dictionary

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +        return "........\r\n"
It seems that a lot of return statements are of the form `.....{}\r\n` can we refactor this return format into a variable? Also, if all commands end with `\r\n` this should be the out terminator

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +            raise AssertionError("Invalid arguments sent")
This is more of a `ValueError` than an `AssertionError`

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +            raise AssertionError("Invalid arguments sent")
This is more of a `ValueError` than an `AssertionError`

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +        self._device.is_paused = False  # TODO logic to check ramp != present output
Don't put TODOs in code, they should be covered by tickets

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +            heater_value = "ON"
Bit of an odd way to do this, just put a ternary in

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +            raise AssertionError("Invalid arguments sent")
This is more of a `ValueError` than an `AssertionError`

2019-10-15 18:31 UTC, DominicOram commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +            self._create_log_message("........ HEATER STATUS", heater_status)
We're creating this log message in either case, put it outside the if statement

2019-11-05 22:52 UTC, Tom-Willemsen requested changes
As Dom mentioned in the previous review, there is lots of code here which isn't actually used by this ticket, or is generally unreachable. I've had a look over it, but not functionally tested it as I don't know how to exercise it.

2019-11-05 22:52 UTC, Tom-Willemsen commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +                                                                                  self._device.ramp_rate)
Presumably the state of the device should be matching exactly one of these clauses. However it's not immediately obvious that that's true.

Maybe we could add a check at the end which will let us know (loudly) if we fail to match any of these conditions?

```suggestion
                                                                                  self._device.ramp_rate)
        else:
            raise ValueError("Didn't match any of the expected conditions")
```

2019-11-05 22:52 UTC, Tom-Willemsen commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +        if paused in ["ON", "1"]:
The lists `["ON", "1"]` and `["OFF", "0"]` seem to be used in a number of places. Maybe we should refactor them into common variables `ON_STATES` and `OFF_STATES`?

2019-11-05 22:52 UTC, Tom-Willemsen commented on lewis_emulators/cryogenic_sms/states.py
> +        print("*********** ENTERED HOLD STATE")
If you want this in the emulator log, I think you need to use `@has_log` on the class and then `self.log.info(...)`

2019-11-05 22:52 UTC, Tom-Willemsen commented on lewis_emulators/cryogenic_sms/states.py
> +        rate = float(device.ramp_rate)
All of the datatype conversions should be occuring in the stream interface, why are these needed here?

2019-11-05 22:52 UTC, Tom-Willemsen commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +            CmdBuilder(self.write_output_mode).spaces().regex("T(?:ESLA)*").spaces().arg("OFF|ON|0|1").spaces().eos()
You added a new `.choice(...)` method to `CmdBuilder` but don't seem to be using it here - is there a reason for that?

2019-11-05 22:52 UTC, Tom-Willemsen commented on lewis_emulators/cryogenic_sms/device.py
> +    def switch_mode(self, mode):
Should this method check that we're not already in the correct mode first?

2019-11-05 22:52 UTC, Tom-Willemsen commented on lewis_emulators/cryogenic_sms/device.py
> +        self.direction = '+'
Probably should use an Enum here.

2019-11-05 22:52 UTC, Tom-Willemsen commented on lewis_emulators/utils/command_builder.py
> +    def choice(self, *choices):
This is very similar to the existing `.enum(...)` method. Maybe we could refactor them to be just one method.

2019-11-12 12:27 UTC, ChrisColeExpControl commented on lewis_emulators/cryogenic_sms/interfaces/stream_interface.py
> +            CmdBuilder(self.write_output_mode).spaces().regex("T(?:ESLA)*").spaces().arg("OFF|ON|0|1").spaces().eos()
`.choice(...)` added options to the command which were _not_ passed as arguments to the resulting function call, so wouldn't be useful here. In fact, it didn't add anything that isn't covered by rather simple regex, so I removed it.

2019-11-12 23:11 UTC, Tom-Willemsen approved these changes

2019-11-12 23:13 UTC, merged