Add emulator for DMA4500M
ISISComputingGroup/EPICS-DeviceEmulator pull request #68
Opened 2020-03-09 13:42 UTC by mr-field

### Description of work
A new emulator has been added for the Anton Paar DMA4500M density meter.

The manual at `\\ISIS\shares\ISIS_Experimental_Controls\Manuals\AntonPaar__DMA4500\XPAIB001EN_T_RefGuide_Gen_SW_Functions_M_v2.96_web` was used as a reference, combined with runnning commands on the actual device. The emulator implements all the commands used by the IOC, plus the `abort` command which I thought might be useful in the future.

Key points:
- The real device can measure many diferent quantities using user-defined methods (see its [wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DMA4500m-Density-Meter)). The emulator assumes the default method used at ISIS, which measures density and temperature
- The device offers a `getrawdata` command to make an "instant" measurement of density and temperature. However, this is not meant to be used for actual measurements, presumably because the error bands are too large. Instead, measurements should be made by calling `start`, checking measurements progress with `finished`, then once it's complete call `getdata` to get the results
- `getdata` can only be called once. When it's called for the first time after a measurement has finished, it returns the result. Otherwise, it returns `no new data`.
- Setting the temperature with `settemperature` on the real device does not block starting a measurement and the user has no way of checking the temperature ramping progress. From the user's point of view, the only consequence of changing the temperature is that, if a measurement is started before the device is done ramping it up or down, the measurement will take longer than usual. I have not modelled this in the emulator, as it did not seem relevant

### Ticket
https://github.com/ISISComputingGroup/IBEX/issues/4948
https://github.com/ISISComputingGroup/IBEX/issues/3922

### Acceptance criteria
- The commands implemented in the emulator return the same values that they woould retuen on the actual device

2020-04-01 17:34 UTC, Alistair-McGann-Tessella requested changes
This is a good emulator, it makes really good use of states! Most of my feedback is that in other emulators we tend to move as much logic as possible away from the stream interface and into the device. The TPG300 and fermi chopper are good examples of this being applied.

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +            CmdBuilder(self.get_raw_data).escape("get").optional(" ").escape("raw").optional(" ").escape("data").eos().build(),
Nit: I can't see any documentation suggesting that you can add optional spaces to these commands. These work, but if they're not necessary consider removing them.

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +    @if_connected
I expect most of the logic of an emulator to lie in the device.py rather than the interface. The TPG300 emulator is a good example of this, most (though not all) of the functions in its stream interface are direct calls to functions on the emulated device. I imagine the functions will look very similar, just in the device.

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +        self._device.measuring = True
This is somewhat subjective, but I would prefer these functions to have an if.. else structure. The behaviour is unchanged, but it gives a visual clue as to what's going on

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +        print(self._device.status)
I'm not sure print statements in a lewis emulator show up the logs. If this is needed, try `self.log.info(self._device.status)`

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +        sample_id = self._device.sample_id or "NaN"
This is confusing syntax, consider using inline if... else (https://stackoverflow.com/a/9797563)

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/device.py
> +            (("ready", "ready"), lambda: self.setting_temperature is True),
I don't think this line does anything, moving from ready to ready isn't a transition?

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +        self._device.measuring = False
It is more typical for interface functions to make direct calls on the device to change parameters rather than mutating them within the interface. This makes it easier to follow the flow of the device.

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +        self._device.target_temperature = temperature
Same as above, it's more common for setters to be held and called in the device class

2020-04-01 17:34 UTC, Alistair-McGann-Tessella commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +        return self.get_data()
Is this the same as self.get_data?

2020-04-09 13:27 UTC, mr-field commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +            CmdBuilder(self.get_raw_data).escape("get").optional(" ").escape("raw").optional(" ").escape("data").eos().build(),
The manual briefly mentions optional spaces at page 44 under "RS-232 Interface Commands". We're not actually using this feature in the IOC, but I thought I'd add it as it was low-effort

2020-04-09 13:28 UTC, mr-field commented on lewis_emulators/dma4500m/interfaces/stream_interface.py
> +    @if_connected
I've now moved most of the logic to the device

2020-04-09 13:35 UTC, mr-field commented on lewis_emulators/dma4500m/device.py
> +            (("ready", "ready"), lambda: self.setting_temperature is True),
Technically it is a transition - it executes the state's `on_entry()` method again, which in this case allows for setting the temperature multiple times in a row. However, I admit it's not a very elegant solution. Should I try changing it to something else?

2020-04-28 10:15 UTC, Alistair-McGann-Tessella approved these changes

2020-04-28 10:15 UTC, Alistair-McGann-Tessella approved these changes

2020-04-28 10:16 UTC, merged